steps:
  - name: node
    args:
      - -v
  - name: gcr.io/cloud-builders/npm
    dir: 'client2'
    args:
      - install
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - gs://${_SETTING_BUCKET}/${_SERVICE_NAME}/env-${_ENV}.env
      - ./client2/.env
  - name: gcr.io/cloud-builders/npm
    dir: 'client2'
    args:
      - run
      - dev
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - gs://${_SETTING_BUCKET}/${_SERVICE_NAME}/settings-${_ENV}.json
      - ./settings.json
  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
